# Generated by Django 4.1.4 on 2022-12-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='user_buy',
            new_name='user_order',
        ),
    ]
