# Generated by Django 4.1.4 on 2022-12-14 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_user_buy_movie_user_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieorder',
            old_name='movie',
            new_name='movie_order',
        ),
        migrations.RenameField(
            model_name='movieorder',
            old_name='user',
            new_name='user_order',
        ),
    ]
