# Generated by Django 4.1.4 on 2022-12-14 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieorder',
            name='movie_order',
        ),
        migrations.AddField(
            model_name='movieorder',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movie_order', to='movies.movie'),
            preserve_default=False,
        ),
    ]
