# Generated by Django 4.1.4 on 2022-12-14 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0007_remove_movieorder_movie_order_movieorder_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user_order',
        ),
        migrations.RemoveField(
            model_name='movieorder',
            name='user_order',
        ),
        migrations.AddField(
            model_name='movieorder',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_movies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movieorder',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_users', to='movies.movie'),
        ),
    ]
