# Generated by Django 4.1.4 on 2022-12-14 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0008_remove_movie_user_order_remove_movieorder_user_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieorder',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movieorder',
            name='user',
        ),
        migrations.AddField(
            model_name='movieorder',
            name='movie_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='movies.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movieorder',
            name='user_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movies_order', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movieorder',
            name='buyed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
